<a href="https://colab.research.google.com/github/Divasdev/BEGINNER-PROJECTS/blob/main/Data_Analysis(Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Setup and Data Acquisition
In this section, we import the necessary libraries (`pandas`, `kagglehub`), download the Stack Overflow 2025 survey dataset, and move the files to a local directory for easier access.

# Stack Overflow Developer Survey 2025 - Data Analysis
This notebook organizes the setup and exploration of the Stack Overflow survey dataset.

In [115]:
import pandas as pd
import kagglehub
import os
import shutil

# 1. Download and set up data
path = kagglehub.dataset_download("aliaslam25/stack-overflow-developer-survey-2025")

# Copy to content folder for easier access
shutil.copy(f"{path}/survey_results_public.csv", "/content/survey_results_public.csv")
shutil.copy(f"{path}/survey_results_schema.csv", "/content/survey_results_schema.csv")

# 2. Configure Display Options
pd.set_option("display.max_columns", 50)
pd.set_option("display.max_rows", 50)

Using Colab cache for faster access to the 'stack-overflow-developer-survey-2025' dataset.

In [116]:
# 3. Load DataFrames
df = pd.read_csv("/content/survey_results_public.csv", low_memory=False,index_col='ResponseId')
schema_df = pd.read_csv("/content/survey_results_schema.csv",index_col="qname")

# 4. Quick Inspection
print(f"Dataset Shape: {df.shape}")
display(df.head(10))

Dataset Shape: (49191, 171)

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,...,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,...,Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,...,Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,...,"Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,...,Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,...,"Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,...,Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,13.0,"Developer, full-stack",NaN,NaN,NaN,No,Personal Project,11.0,1.0,2.0,6.0,4.0,7.0,13.0,8.0,...,"Yes, somewhat",Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,NaN,NaN,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,Sentry,NaN,ChatGPT;Claude Code;Google Gemini,NaN,When I don’t trust AI’s answers;When I need he...,NaN,6240.0,6.0
8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Blogs or p...,30.0,"Architect, software or solutions",Less than 20 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Personal Project,12.0,2.0,1.0,10.0,4.0,5.0,8.0,6.0,...,"Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have concerns about the security and privacy...,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0
9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,15.0,Data engineer,"5,000 to 9,999 employees",Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Personal Project,5.0,7.0,13.0,4.0,9.0,8.0,12.0,2.0,...,NaN,Software engineering;Data and analytics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0
10,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,10.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,No,Work,13.0,2.0,5.0,1.0,6.0,9.0,10.0,7.0,...,"No, but my development work has changed somewh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,The cost of using certain AI agent platforms i...,It takes significant time and effort to learn ...,I have concerns about the security and privacy...,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem;W...,NaN,5400.0,4.0

### 2. Loading and Inspecting Data
Here we load the main survey results into a DataFrame (`df`) and the metadata into `schema_df`. We set the `ResponseId` as the index to make row lookups more intuitive.

In [117]:
# 5. Schema Inspection
display(schema_df)

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [118]:
df.columns

Index(['MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl',
       'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=171)

In [119]:
df['EdLevel']

ResponseId
1          Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
2                      Associate degree (A.A., A.S., etc.)
3             Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4             Bachelor’s degree (B.A., B.S., B.Eng., etc.)
5          Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
                               ...
49187         Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49188    Some college/university study without earning ...
49189      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49190       Professional degree (JD, MD, Ph.D, Ed.D, etc.)
49191    Some college/university study without earning ...
Name: EdLevel, Length: 49191, dtype: object

In [120]:
df.loc[:5,"Employment":'WorkExp']

,Employment,EmploymentAddl,WorkExp
ResponseId,,,
1,Employed,"Caring for dependents (children, elderly, etc.)",8.0
2,Employed,NaN,2.0
3,"Independent contractor, freelancer, or self-em...",None of the above,10.0
4,Employed,None of the above,4.0
5,"Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0

In [121]:
df["Employment"].value_counts()

Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64

In [122]:
df.loc[1]

MainBranch                              I am a developer by profession
Age                                                    25-34 years old
EdLevel                Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
Employment                                                    Employed
EmploymentAddl         Caring for dependents (children, elderly, etc.)
                                            ...
AIAgentExtWrite                                                    NaN
AIHuman                                When I don’t trust AI’s answers
AIOpen                           Troubleshooting, profiling, debugging
ConvertedCompYearly                                            61256.0
JobSat                                                            10.0
Name: 1, Length: 171, dtype: object

In [123]:
schema_df.loc['Employment','question']

'Which of the following best describes your current employment status?<br>'

In [124]:
schema_df.sort_index(ascending=True)

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
...,...,...,...,...,...
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

### 3. Salary and Compensation Analysis
We search the schema for keywords like 'salary' to identify which columns contain pay information. We then rename `ConvertedCompYearly` to `salaryUSD` to make it easier to work with.

In [125]:

# Search for 'salary' or 'compensation' in the schema
salary_info = schema_df[schema_df['question'].str.contains('salary|compensation|pay', case=False, na=False)]

print("Matching columns in schema:")
display(salary_info[['question']])

print("\nLikely relevant columns in df:")
salary_cols = [col for col in df.columns if 'Comp' in col or 'Salary' in col]
print(salary_cols)

Matching columns in schema:

                                                    question
qname
CompTotal  What is your current total <b>annual</b> compe...

Likely relevant columns in df:
['CompTotal', 'AIComplex', 'ConvertedCompYearly']

In [126]:
countries=["United States of America",'Australia','India','Sweden','Germany']
filt=df["Country"].isin(countries)

In [127]:
df.loc[filt,'Country']

ResponseId
14                          India
16                          India
17                      Australia
19                        Germany
22       United States of America
                   ...
49156                       India
49158    United States of America
49176                     Germany
49178    United States of America
49179                     Germany
Name: Country, Length: 14225, dtype: object

In [128]:
lang_filter=df["LanguageHaveWorkedWith"].str.contains('Python',na=False)

In [129]:
df.loc[lang_filter,"LanguageHaveWorkedWith"]

ResponseId
5        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
8        Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
9                                        Java;Python;Scala
16       Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...
18                          HTML/CSS;JavaScript;Python;SQL
                               ...
49144            HTML/CSS;JavaScript;Python;SQL;TypeScript
49146    Assembly;Bash/Shell (all shells);C;C++;Python;...
49176    Bash/Shell (all shells);C#;C++;GDScript;HTML/C...
49177    Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
49178    Bash/Shell (all shells);HTML/CSS;Lisp;PowerShe...
Name: LanguageHaveWorkedWith, Length: 18466, dtype: object

In [130]:
lang_filter

ResponseId
1        False
2        False
3        False
4        False
5         True
         ...
49187    False
49188    False
49189    False
49190    False
49191    False
Name: LanguageHaveWorkedWith, Length: 49191, dtype: bool

In [131]:
df.rename(columns={'ConvertedCompYearly':"salaryUSD"},inplace=True)
df.columns

Index(['MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl',
       'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'salaryUSD', 'JobSat'],
      dtype='object', length=171)

### 4. Data Filtering and Sorting
In these steps, we practice filtering the data by specific countries (USA, India, etc.) and sorting the entire dataset by Country name to see the geographic distribution.

In [132]:
df['salaryUSD']

ResponseId
1         61256.0
2        104413.0
3         53061.0
4         36197.0
5         60000.0
           ...
49187         NaN
49188         NaN
49189         NaN
49190         NaN
49191         NaN
Name: salaryUSD, Length: 49191, dtype: float64

In [133]:
df['Employment']

ResponseId
1                                                 Employed
2                                                 Employed
3        Independent contractor, freelancer, or self-em...
4                                                 Employed
5        Independent contractor, freelancer, or self-em...
                               ...
49187                                             Employed
49188                                             Employed
49189                                             Employed
49190    Independent contractor, freelancer, or self-em...
49191                                              Student
Name: Employment, Length: 49191, dtype: object

In [134]:
df['Employment'].replace({'Employed':'Great','Student':'Work-Hard'})

ResponseId
1                                                    Great
2                                                    Great
3        Independent contractor, freelancer, or self-em...
4                                                    Great
5        Independent contractor, freelancer, or self-em...
                               ...
49187                                                Great
49188                                                Great
49189                                                Great
49190    Independent contractor, freelancer, or self-em...
49191                                            Work-Hard
Name: Employment, Length: 49191, dtype: object

In [135]:
df.sort_values(by='Country')

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,...,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,salaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
6836,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"No, I learned something that was not related t...",NaN,4.0,"Developer, back-end",NaN,NaN,NaN,NaN,School,4.0,2.0,7.0,9.0,5.0,1.0,8.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,AI,NaN,10.0
6010,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",5.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,8.0,"Developer, full-stack",20 to 99 employees,NaN,NaN,No,Work,9.0,2.0,1.0,4.0,7.0,6.0,8.0,3.0,...,"Yes, to a great extent",Software engineering;Business process automati...,Integration with external agents and APIs,AI agents have improved the quality of my code...,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,I have concerns about the security and privacy...,I am concerned about the accuracy of the infor...,NaN,NaN,Integrating AI agents with my existing tools a...,Redis;supabase,NaN,Llama Index;Ollama;OpenRouter,NaN,Sentry;Grafana + Prometheus,NaN,ChatGPT;GitHub Copilot;Tabnine;Lovable.dev,NaN,I don’t think I’ll need help from people anymore,Problem-Solving and Critical Thinking,986.0,8.0
15708,I am a developer by profession,Prefer not to say,NaN,"Independent contractor, freelancer, or self-em...",Transitioning to retirement (gradually reducin...,NaN,"Yes, I am new to coding or currently a student",Games or coding challenges,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,NaN,AI/ML engineer,NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7077,"I am not primarily a developer, but I write co...",25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (less than 10 hours per w...,7.0,"Yes, I am new to coding or currently a student",AI CodeGen tools or AI-enabled apps,"Yes, I learned how to use AI-enabled tools req...","Other online resources (e.g. standard search, ...",1.0,Project manager,"1,000 to 4,999 employees",People manager,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,1.0,2.0,7.0,8.0,5.0,3.0,6.0,4.0,...,"Yes, to a great extent",Business process automation,Agent/multi-agent orchestration,AI agents have helped me solve complex problem...,NaN,Write in the most significant benefit if not l...,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Write in the most significant challenge if not...,NaN,ChromaDB,no,Ollama,NaN,Metero,NaN,ChatGPT;Google Gemini;AgentGPT;Perplexity,NaN,When I’m stuck and can’t explain the problem,yes,8450.0,NaN
19816,I am learning to code,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,None of the above;Attending school (part-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,2.0,Student,NaN,NaN,NaN,NaN,Personal Project,3.0,5.0,9.0,1.0,2.0,6.0,7.0,4.0,...,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,6.0,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 5. Descriptive Statistics
We calculate central tendencies like the `median` for numerical columns and use `value_counts` to see the distribution of categorical data like `Employment` status.

In [136]:
df['Country'].head(30)

ResponseId
1                                               Ukraine
2                                           Netherlands
3                                               Ukraine
4                                               Ukraine
5                                               Ukraine
6                                               Ukraine
7                                               Ukraine
8                                               Ukraine
9                                               Ukraine
10                                              Ukraine
11                                              Ukraine
12                                              Ukraine
13                                              Ukraine
14                                                India
15                                              Georgia
16                                                India
17                                            Australia
18                                               Greece
19                                              Germany
20                                           Bangladesh
21                                               Brazil
22                             United States of America
23                             United States of America
24                                          Netherlands
25                                            Lithuania
26    United Kingdom of Great Britain and Northern I...
27                                              Ireland
28                                               Sweden
29                                   Dominican Republic
30                             United States of America
Name: Country, dtype: object

In [137]:
df['salaryUSD'].head(15)

ResponseId
1      61256.0
2     104413.0
3      53061.0
4      36197.0
5      60000.0
6     120000.0
7       6240.0
8      72000.0
9      70000.0
10      5400.0
11     65691.0
12     14400.0
13      1099.0
14         NaN
15         NaN
Name: salaryUSD, dtype: float64

In [138]:
df['salaryUSD'].median()

75320.0

In [139]:
df.select_dtypes(include='number').median()

WorkExp             10.0
YearsCode           14.0
TechEndorse_1        9.0
TechEndorse_2        4.0
TechEndorse_3        4.0
                  ...
SO_Actions_7         5.0
SO_Actions_10        8.0
SO_Actions_15       10.0
salaryUSD        75320.0
JobSat               8.0
Length: 52, dtype: float64

In [140]:
df.describe()

,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,ToolCountWork,ToolCountPersonal,CompTotal,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,salaryUSD,JobSat
count,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,24943.000000,24943.000000,24943.000000,...,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,27611.000000,25582.000000,2.486600e+04,26260.000000,24340.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,4.370841,4.431661,9.854315,8.307948,4.524067,5.925567,4.991710,4.048980,3.799323,4.365831,5.059867,5.508538,9.945766,6.867738,5.216173,7.455719,...,8.194965,5.884096,7.367799,6.744658,7.512569,5.703283,8.563324,8.679349,14.687487,7.826685,17.734852,8.545579,2.234198e+70,4.907845,3.339770,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,2.357058,2.620901,1.975692,2.202164,2.282867,2.301937,2.294707,2.607443,2.499468,2.557152,2.533541,2.906146,2.087463,3.741490,3.660632,3.726759,...,3.801257,3.900813,4.118532,3.888845,3.847265,4.110528,3.545288,3.633175,1.898188,4.077460,269.810134,44.664738,3.523096e+72,2.682204,2.411404,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,2.000000,2.000000,10.000000,8.000000,3.000000,4.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,10.000000,4.000000,2.000000,4.000000,...,5.000000,2.000000,4.000000,3.000000,4.000000,2.000000,6.000000,6.000000,15.000000,4.000000,4.000000,3.000000,5.500000e+04,3.000000,1.000000,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,4.000000,4.000000,10.000000,9.000000,4.000000,6.000000,5.000000,4.000000,3.000000,4.000000,5.000000,6.000000,10.000000,6.000000,4.000000,7.000000,...,8.000000,5.000000,7.000000,6.000000,7.000000,5.000000,9.000000,9.000000,15.000000,8.000000,6.000000,5.000000,1.050000e+05,5.000000,2.000000,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,6.000000,7.000000,10.000000,9.000000,6.000000,8.000000,7.000000,6.000000,6.000000,6.000000,7.000000,8.000000,10.000000,10.000000,8.000000,11.000000,...,11.000000,9.000000,11.000000,10.000000,11.000000,9.000000,12.000000,12.000000,15.000000,11.000000,10.000000,7.000000,2.400000e+05,7.000000,5.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000,15.000000,16.000000,15.000000,15.000000,15.000000,...,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,10000.000000,1000.000000,5.555556e+74,15.000000,10.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [141]:
df["WorkExp"].describe()

count    42893.000000
mean        13.367403
std         10.800117
min          1.000000
25%          5.000000
50%         10.000000
75%         20.000000
max        100.000000
Name: WorkExp, dtype: float64

In [142]:
df['salaryUSD'].count()

np.int64(23947)

In [143]:
df["Employment"]

ResponseId
1                                                 Employed
2                                                 Employed
3        Independent contractor, freelancer, or self-em...
4                                                 Employed
5        Independent contractor, freelancer, or self-em...
                               ...
49187                                             Employed
49188                                             Employed
49189                                             Employed
49190    Independent contractor, freelancer, or self-em...
49191                                              Student
Name: Employment, Length: 49191, dtype: object

In [144]:
df["Employment"].value_counts()

Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64

### 6. Grouping Data by Country
Using `groupby`, we create a `country_grp` object. This allows us to perform aggregate functions (like mean or median salary) specifically for each country rather than the whole dataset at once.

In [145]:
df['CommPlatformHaveWorkedWith'].value_counts(normalize=True)

CommPlatformHaveWorkedWith
Stack Overflow                                                                                                                                                              0.029636
Stack Overflow;Stack Exchange                                                                                                                                               0.019724
Stack Overflow;Stack Exchange;GitHub (public projects, not private repos)                                                                                                   0.017795
Stack Overflow;GitHub (public projects, not private repos)                                                                                                                  0.016032
Stack Overflow;Stack Exchange;Reddit;GitHub (public projects, not private repos)                                                                                            0.012905
                                                                                                                                                                              ...
Stack Overflow;Discord;Dev.to;Hacker News;Hashnode;GitHub (public projects, not private repos);Slack (public channels, not work);X;Kaggle;YouTube;Twitch;Substack;Medium    0.000033
Stack Overflow;Reddit;GitHub (public projects, not private repos);Slack (public channels, not work);Bluesky;Kaggle;YouTube;Medium;Company-sponsored forums                  0.000033
Discord;Reddit;Dev.to;GitHub (public projects, not private repos);Slack (public channels, not work);Bluesky;YouTube                                                         0.000033
Stack Overflow;Discord;Slack (public channels, not work);X;YouTube;LinkedIn;Medium                                                                                          0.000033
Slack (public channels, not work);X;YouTube;LinkedIn                                                                                                                        0.000033
Name: proportion, Length: 6108, dtype: float64

In [146]:
df['Country'].value_counts()

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
                                                        ...
Lesotho                                                    1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, Length: 177, dtype: int64

In [147]:
country_grp=df.groupby(["Country"])

### 7. String Operations and Python Usage
Finally, we use string methods (`.str.contains`) combined with our groups to find out how many people in each country use Python, eventually calculating this as a percentage of that country's total respondents.

In [148]:
country_grp.get_group('India')

/tmp/ipykernel_907/421256909.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('India')

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,...,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,salaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,...,"Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,...,Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49133,I code primarily as a hobby,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not employed,NaN,NaN,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Videos (not associated ...,"No, I learned something that was not related t...",NaN,3.0,Student,NaN,NaN,NaN,NaN,Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,Maths,NaN,NaN
49142,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,1.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,5.0,Data engineer,20 to 99 employees,NaN,In-person,"Yes, I influenced the purchase of a substantia...",Work,4.0,6.0,1.0,3.0,5.0,2.0,8.0,9.0,...,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49150,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (less than 10 hours per w...,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,10.0,"Developer, front-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,4.0,5.0,6.0,3.0,8.0,1.0,9.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
49155,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,20.0,"Architect, software or solutions",100 to 499 employees,People manager,In-person,"Yes, I influenced the purchase of a substantia...",Work,2.0,5.0,4.0,9.0,3.0,7.0,8.0,6.0,...,"Yes, somewhat",Software engineering;Business process automati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
49156,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc....",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,8.0,"Developer, full-stack","10,000 or more employees",Individual contributor,In-person,"Yes, I influenced the purchase of a substantia...",Personal Project,6.0,3.0,7.0,5.0,9.0,2.0,1.0,4.0,...,"Yes, to a great extent",Software engineering,NaN,AI agents have improved the quality of my code...,NaN,AI agents have helped me automate repetitive t...,AI agents have increased my productivity.;AI a...,AI agents have improved collaboration within m...,Integrating AI agents with my existing tools a...,NaN,I have concerns about the security and privacy...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,I think this will not obsolete to developer bu...,NaN,6.0

In [149]:
filte=df['Country']=='India'
df.loc[filte]['CommPlatformHaveWorkedWith'].value_counts()

CommPlatformHaveWorkedWith
Stack Overflow                                                                                                                                                                                                               57
Stack Overflow;Stack Exchange                                                                                                                                                                                                40
Stack Overflow;YouTube                                                                                                                                                                                                       22
YouTube;LinkedIn                                                                                                                                                                                                             18
Stack Overflow;GitHub (public projects, not private repos)                                                                                                                                                                   15
                                                                                                                                                                                                                             ..
Discord;Dev.to;Hashnode;GitHub (public projects, not private repos);Slack (public channels, not work);X;YouTube;LinkedIn;Medium                                                                                               1
Stack Overflow;Stack Exchange;GitHub (public projects, not private repos);Kaggle;YouTube;LinkedIn;Medium                                                                                                                      1
Stack Overflow;Discord;Hashnode;YouTube;LinkedIn;Medium                                                                                                                                                                       1
Stack Overflow;Stack Exchange;Discord;YouTube;Medium                                                                                                                                                                          1
Stack Overflow;Discord;Reddit;Dev.to;Hacker News;Hashnode;GitHub (public projects, not private repos);Slack (public channels, not work);Bluesky;X;Kaggle;YouTube;Twitch;LinkedIn;Substack;Medium;Company-sponsored forums     1
Name: count, Length: 1006, dtype: int64

In [150]:
country_grp['CommPlatformHaveWorkedWith'].value_counts().loc['India']

CommPlatformHaveWorkedWith
Stack Overflow                                                57
Stack Overflow;Stack Exchange                                 40
Stack Overflow;YouTube                                        22
YouTube;LinkedIn                                              18
Stack Overflow;GitHub (public projects, not private repos)    15
                                                              ..
X;Kaggle;YouTube;LinkedIn                                      1
X;YouTube                                                      1
X;YouTube;Twitch;LinkedIn;Medium                               1
YouTube;Company-sponsored forums                               1
YouTube;Medium                                                 1
Name: count, Length: 1006, dtype: int64

In [151]:
country_grp['salaryUSD'].median().loc['India']

np.float64(17029.0)

In [152]:
country_grp['salaryUSD'].agg(['median','mean']).loc[['United States of America','India']]

                            median           mean
Country
United States of America  150000.0  179804.501621
India                      17029.0   44291.789234

In [153]:
filte=df['Country']=='India'
df.loc[filte]['LanguageHaveWorkedWith'].str.contains('Python').sum()

1162

In [154]:
country_grp['LanguageHaveWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [155]:
max(country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum()))

4221

In [156]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              4
Albania                                 10
Algeria                                 23
Andorra                                  2
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    23
Viet Nam                                78
Yemen                                    6
Zambia                                   7
Zimbabwe                                 7
Name: LanguageHaveWorkedWith, Length: 177, dtype: int64

In [157]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x)

Country      ResponseId
Afghanistan  6010          Bash/Shell (all shells);Go;HTML/CSS;JavaScript...
             6836                                                     Python
             7077                              Ada;JavaScript;PHP;PowerShell
             7167                                                        NaN
             7925                           Dart;HTML/CSS;JavaScript;PHP;SQL
                                                 ...
Zimbabwe     41192                                                     R;SQL
             44223                                                       NaN
             46132                                                Python;VBA
             46507                                                       NaN
             49000                            HTML/CSS;JavaScript;Python;SQL
Name: LanguageHaveWorkedWith, Length: 35437, dtype: object

### Percentage of Developers who know Python per Country

To calculate the percentage of developers who know Python in each country, we first count the number of developers in each country who have indicated 'Python' in their 'LanguageHaveWorkedWith' response. Then, we divide this count by the total number of respondents for each country and multiply by 100.

In [158]:
python_users_per_country = country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
total_respondents_per_country = country_grp['Country'].count()

python_percentage_per_country = (python_users_per_country / total_respondents_per_country) * 100

# Sort the results in descending order
display(python_percentage_per_country.sort_values(ascending=False))

Country
Cape Verde      100.0
Lesotho         100.0
Mali            100.0
Niger           100.0
Mongolia        100.0
                ...
San Marino        0.0
Sierra Leone      0.0
Sudan             0.0
Timor-Leste       0.0
Turkmenistan      0.0
Length: 177, dtype: float64